# 使用 Node 的版本
FROM node:12.18.3-stretch
#USER node

# Node 環境設定為 production
ENV NODE_ENV development
RUN yarn global add @vue/cli
RUN vue --version

# Node 在容器內的位置
WORKDIR /usr/src/app

# 複製網站內容程式碼
COPY app /usr/src/app
RUN cd /usr/src/app && \
    ls -l && \
    yarn install && \
    yarn build && \
    ls -l

# 開放對外的 port
EXPOSE 3000

# 執行專案
CMD yarn express:run
