# 使用 Node 的版本
FROM node:12.18.3-stretch AS builder

ENV NODE_ENV development

# Node 在容器內的位置
WORKDIR /usr/src/app

RUN yarn global add @vue/cli

# 複製網站內容程式碼
COPY ./* /user/src/app/
# BUILD
RUN cd /usr/src/app && \ yarn build

FROM docker.io/bitnami/apache:2.4-debian-10
COPY --from=builder /user/src/app /app
